{
  "patch_version": "1.0.0",
  "manager_versions": ["4.5.0","4.5"],
  "community": true,
  "premium": true,
  "patches": [
    {
      "patch_file": "4.5_make_validate_agent_recover__operations.py.patch",
      "md5sum": "1ef98b642afbd2a36d146e6e438b9e61",
      "destinations": ["/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_agent/operations.py"]
    }
  ],
  "affected_services": [
    "cloudify-mgmtworker"
  ],
  "md5sums_before": {
    "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_agent/operations.py": ["2024a642ab4e7787964cd3c430c998c5"]
  },
  "md5sums_after": {
    "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_agent/operations.py": ["081e0d2000427cd64e2836d7ec9f4026"]
  }
}
